### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ashutoshpw** [davidadamojr/TextRank#9]
Installation Aborted with following text:

```
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-HjUAJe-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/numpy
```

```
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
```

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)
```

**Comment by Reyeselda95** [comment]
Did you tried updating pip?
run `sudo pip install -U pip` and then try install again.
The Unicode error is because of the default configuration of Python2.7. You need to set your default decode configuration to UTF-8.
```python
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```
You need to run this before trying to run it in order to set your encoding to UTF-8. If it don't work running it outside the program, try adding those lines into the setup.py file of the repository and install again with `sudo python setup.py install`
